{"uuid": "a7f47912-36a2-4974-9160-57966451627d", "children": ["65fdf4ff-37ac-44ad-8502-6f0c616d59fa"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=138.0.7204.35)\nStacktrace:\n0   chromedriver                        0x0000000100a71660 cxxbridge1$str$ptr + 2724392\n1   chromedriver                        0x0000000100a695d8 cxxbridge1$str$ptr + 2691488\n2   chromedriver                        0x00000001005ba0fc cxxbridge1$string$len + 90068\n3   chromedriver                        0x00000001005b2778 cxxbridge1$string$len + 58960\n4   chromedriver                        0x00000001005a53d8 cxxbridge1$string$len + 4784\n5   chromedriver                        0x00000001005a6dd8 cxxbridge1$string$len + 11440\n6   chromedriver                        0x00000001005a582c cxxbridge1$string$len + 5892\n7   chromedriver                        0x00000001005a5180 cxxbridge1$string$len + 4184\n8   chromedriver                        0x00000001005a4ecc cxxbridge1$string$len + 3492\n9   chromedriver                        0x00000001005a2c84 chromedriver + 191620\n10  chromedriver                        0x00000001005a36e0 chromedriver + 194272\n11  chromedriver                        0x00000001005bd160 cxxbridge1$string$len + 102456\n12  chromedriver                        0x000000010064330c cxxbridge1$string$len + 651748\n13  chromedriver                        0x0000000100642874 cxxbridge1$string$len + 649036\n14  chromedriver                        0x00000001005f5790 cxxbridge1$string$len + 333416\n15  chromedriver                        0x0000000100a35440 cxxbridge1$str$ptr + 2478088\n16  chromedriver                        0x0000000100a386a8 cxxbridge1$str$ptr + 2490992\n17  chromedriver                        0x0000000100a16328 cxxbridge1$str$ptr + 2350832\n18  chromedriver                        0x0000000100a38f64 cxxbridge1$str$ptr + 2493228\n19  chromedriver                        0x0000000100a07414 cxxbridge1$str$ptr + 2289628\n20  chromedriver                        0x0000000100a59090 cxxbridge1$str$ptr + 2624600\n21  chromedriver                        0x0000000100a5921c cxxbridge1$str$ptr + 2624996\n22  chromedriver                        0x0000000100a69214 cxxbridge1$str$ptr + 2690524\n23  libsystem_pthread.dylib             0x000000019397ec0c _pthread_start + 136\n24  libsystem_pthread.dylib             0x0000000193979b80 thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/maria.kosheleva/otus_final_project/conftest.py\", line 129, in browser\n    driver.get(url)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750508812561, "stop": 1750508813650}], "start": 1750508812561, "stop": 1750508813683}