{"uuid": "27e57ccc-5886-4d3a-aabe-f1691f94fdea", "children": ["8d0e2880-556b-48ba-9188-57eae12c6767"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=138.0.7204.35)\nStacktrace:\n0   chromedriver                        0x0000000104c7d660 cxxbridge1$str$ptr + 2724392\n1   chromedriver                        0x0000000104c755d8 cxxbridge1$str$ptr + 2691488\n2   chromedriver                        0x00000001047c60fc cxxbridge1$string$len + 90068\n3   chromedriver                        0x00000001047be778 cxxbridge1$string$len + 58960\n4   chromedriver                        0x00000001047b13d8 cxxbridge1$string$len + 4784\n5   chromedriver                        0x00000001047b2dd8 cxxbridge1$string$len + 11440\n6   chromedriver                        0x00000001047b182c cxxbridge1$string$len + 5892\n7   chromedriver                        0x00000001047b1180 cxxbridge1$string$len + 4184\n8   chromedriver                        0x00000001047b0ecc cxxbridge1$string$len + 3492\n9   chromedriver                        0x00000001047aec84 chromedriver + 191620\n10  chromedriver                        0x00000001047af6e0 chromedriver + 194272\n11  chromedriver                        0x00000001047c9160 cxxbridge1$string$len + 102456\n12  chromedriver                        0x000000010484f30c cxxbridge1$string$len + 651748\n13  chromedriver                        0x000000010484e874 cxxbridge1$string$len + 649036\n14  chromedriver                        0x0000000104801790 cxxbridge1$string$len + 333416\n15  chromedriver                        0x0000000104c41440 cxxbridge1$str$ptr + 2478088\n16  chromedriver                        0x0000000104c446a8 cxxbridge1$str$ptr + 2490992\n17  chromedriver                        0x0000000104c22328 cxxbridge1$str$ptr + 2350832\n18  chromedriver                        0x0000000104c44f64 cxxbridge1$str$ptr + 2493228\n19  chromedriver                        0x0000000104c13414 cxxbridge1$str$ptr + 2289628\n20  chromedriver                        0x0000000104c65090 cxxbridge1$str$ptr + 2624600\n21  chromedriver                        0x0000000104c6521c cxxbridge1$str$ptr + 2624996\n22  chromedriver                        0x0000000104c75214 cxxbridge1$str$ptr + 2690524\n23  libsystem_pthread.dylib             0x000000019397ec0c _pthread_start + 136\n24  libsystem_pthread.dylib             0x0000000193979b80 thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/maria.kosheleva/otus_final_project/conftest.py\", line 129, in browser\n    driver.get(url)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750508621835, "stop": 1750508623015}], "start": 1750508621835, "stop": 1750508623046}