{"uuid": "3c38112d-b3da-437b-b591-126e14592712", "children": ["0aaeceb7-fdff-44fa-a9a4-69d811fc83d4"], "befores": [{"name": "browser", "status": "passed", "start": 1750520660528, "stop": 1750520661465}], "afters": [{"name": "browser::1", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.35)\nStacktrace:\n0   chromedriver                        0x0000000100acd660 cxxbridge1$str$ptr + 2724392\n1   chromedriver                        0x0000000100ac55d8 cxxbridge1$str$ptr + 2691488\n2   chromedriver                        0x00000001006160fc cxxbridge1$string$len + 90068\n3   chromedriver                        0x00000001005f0098 chromedriver + 131224\n4   chromedriver                        0x000000010068556c cxxbridge1$string$len + 545860\n5   chromedriver                        0x000000010069e3b4 cxxbridge1$string$len + 647820\n6   chromedriver                        0x0000000100651790 cxxbridge1$string$len + 333416\n7   chromedriver                        0x0000000100a91440 cxxbridge1$str$ptr + 2478088\n8   chromedriver                        0x0000000100a946a8 cxxbridge1$str$ptr + 2490992\n9   chromedriver                        0x0000000100a72328 cxxbridge1$str$ptr + 2350832\n10  chromedriver                        0x0000000100a94f64 cxxbridge1$str$ptr + 2493228\n11  chromedriver                        0x0000000100a63414 cxxbridge1$str$ptr + 2289628\n12  chromedriver                        0x0000000100ab5090 cxxbridge1$str$ptr + 2624600\n13  chromedriver                        0x0000000100ab521c cxxbridge1$str$ptr + 2624996\n14  chromedriver                        0x0000000100ac5214 cxxbridge1$str$ptr + 2690524\n15  libsystem_pthread.dylib             0x000000019397ec0c _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000193979b80 thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/maria.kosheleva/otus_final_project/conftest.py\", line 153, in browser\n    body=driver.get_screenshot_as_png(),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 853, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 864, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750520664131, "stop": 1750520664132}, {"name": "browser::end", "status": "passed", "start": 1750520664132, "stop": 1750520664209}], "start": 1750520660528, "stop": 1750520664209}